# Generated by Django 5.1.7 on 2025-10-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_add_currency_to_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='previous_close',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Previous day closing price for calculating daily changes', max_digits=10, null=True),
        ),
    ]
