# Generated by Django 5.1.7 on 2025-10-09 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_stock_previous_close'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRefreshStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('last_refreshed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Stock refresh status',
                'verbose_name_plural': 'Stock refresh status',
            },
        ),
    ]
