# Generated by Django 5.1.7 on 2025-10-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stockrefreshstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='company_code',
            field=models.CharField(blank=True, default='', help_text='Identifier provided by the exchange (e.g., BVL company code)', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_local',
            field=models.BooleanField(default=False, help_text='True when the instrument corresponds to a local BVL listing'),
        ),
    ]
