# Generated by Django 5.1.7 on 2025-11-08 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_stock_company_code_stock_is_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='stocks.stock')),
            ],
            options={
                'db_table': 'stocks_historicalstockprice',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('stock', 'date'), name='unique_stock_date')],
            },
        ),
    ]
