# Generated by Django 5.1.7 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_historicalstockprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='previous_close_date',
            field=models.DateField(blank=True, help_text='Trading date associated with previous_close', null=True),
        ),
    ]
