[pytest]
DJANGO_SETTINGS_MODULE = TradeSimulator.test_settings
pythonpath = backend
python_files = _test*.py test_*.py
testpaths =
    backend/portfolio/tests
    backend/stocks/tests
    backend/users/tests
    backend/TradeSimulator/tests
addopts = --tb=short --strict-markers --disable-warnings
