web: gunicorn TradeSimulator.wsgi:application --bind 0.0.0.0:$PORT --workers 3
worker: celery -A TradeSimulator worker --loglevel=info
beat: python manage.py sync_periodic_tasks && celery -A TradeSimulator beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
