# Generated by Django 5.1.7 on 2025-04-12 21:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holding',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='holding',
            name='portfolio_h_portfol_294dec_idx',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Initial portfolio created automatically for new users'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
    ]
