# Generated by Django 5.1.7 on 2025-04-15 00:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_unique_default_portfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holding',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='executed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='average_purchase_price',
            field=models.DecimalField(decimal_places=2, help_text='Weighted average price per share', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='holding',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Number of shares held', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy Order'), ('SELL', 'Sell Order'), ('DEPOSIT', 'Cash Deposit')], max_length=10),
        ),
    ]
