# Generated by Django 5.1.7 on 2025-04-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
