# Generated by Django 5.1.7 on 2025-04-16 18:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_transaction_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, default='Default portfolio'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='My Portfolio', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
