# Generated by Django 5.1.7 on 2025-04-17 01:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_portfolio_description_remove_portfolio_name_and_more'),
        ('stocks', '0002_stock_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_weighted_return', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Annualized time-weighted return', max_digits=10)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name_plural': 'Portfolio Performances',
            },
        ),
        migrations.CreateModel(
            name='DailyPortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('investment_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_deposits', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['portfolio', 'date'], name='portfolio_d_portfol_69063d_idx')],
                'unique_together': {('portfolio', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RealizedPNL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('pnl', models.DecimalField(decimal_places=2, help_text='Realized profit/loss (positive for gains)', max_digits=15)),
                ('realized_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realized_pnls', to='portfolio.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realized_pnl', to='portfolio.transaction')),
            ],
            options={
                'ordering': ['-realized_at'],
                'indexes': [models.Index(fields=['portfolio', 'realized_at'], name='portfolio_r_portfol_1edff9_idx'), models.Index(fields=['stock', 'realized_at'], name='portfolio_r_stock_i_3fef05_idx')],
            },
        ),
    ]
