# Generated by Django 5.1.7 on 2025-05-05 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_portfolioperformance_dailyportfoliosnapshot_and_more'),
        ('stocks', '0002_stock_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='portfolio_t_transac_dded9c_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='portfolio_timestamp_idx',
            old_name='portfolio_t_portfol_843795_idx',
        ),
        migrations.AddField(
            model_name='holding',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False if position fully sold'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the portfolio’s purpose or goals'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='My Portfolio', help_text='User-defined name for this portfolio', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='idempotency_key',
            field=models.UUIDField(db_index=True, default=1, editable=False, help_text='Unique identifier for preventing duplicate processing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holding',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Number of shares held'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy Order'), ('SELL', 'Sell Order'), ('DEPOSIT', 'Cash Deposit'), ('WITHDRAWAL', 'Cash Withdrawal')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('portfolio', 'idempotency_key')},
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['stock'], name='holding_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user', 'is_deleted'], name='portfolio_p_user_id_45ccd5_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['is_default'], name='portfolio_p_is_defa_f9c757_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['portfolio', 'idempotency_key'], name='portfolio_idempotency_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'timestamp'], name='type_timestamp_idx'),
        ),
        migrations.AddField(
            model_name='historicalstockprice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='stocks.stock'),
        ),
        migrations.AddConstraint(
            model_name='historicalstockprice',
            constraint=models.UniqueConstraint(fields=('stock', 'date'), name='unique_stock_date'),
        ),
    ]
