# Generated by Django 5.1.7 on 2025-05-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_historicalstockprice_and_more'),
        ('stocks', '0002_stock_is_active'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailyportfoliosnapshot',
            name='portfolio_d_portfol_69063d_idx',
        ),
        migrations.AddIndex(
            model_name='dailyportfoliosnapshot',
            index=models.Index(fields=['date', 'portfolio'], name='date_portfolio_idx'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('is_active', False), _connector='OR'), name='active_holding_positive_quantity'),
        ),
    ]
