# Generated by Django 5.1.7 on 2025-05-05 07:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_dailyportfoliosnapshot_portfolio_d_portfol_69063d_idx_and_more'),
        ('stocks', '0002_stock_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='idempotency_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for preventing duplicate processing'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.CheckConstraint(condition=models.Q(('average_purchase_price__gt', 0)), name='holding_price_positive'),
        ),
    ]
