# Generated by Django 5.1.7 on 2025-05-05 23:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_transaction_idempotency_key_and_more'),
        ('stocks', '0002_stock_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('quantity', models.PositiveIntegerField()),
                ('average_purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='portfolioperformance',
            name='total_withdrawals',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cash withdrawn from portfolio', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['timestamp'], name='transaction_timestamp_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.CheckConstraint(condition=models.Q(('cash_balance__gte', 0)), name='cash_balance_non_negative'),
        ),
        migrations.AddField(
            model_name='holdingsnapshot',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_snapshots', to='portfolio.portfolio'),
        ),
        migrations.AddField(
            model_name='holdingsnapshot',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock'),
        ),
        migrations.AddIndex(
            model_name='holdingsnapshot',
            index=models.Index(fields=['date', 'portfolio'], name='holding_date_portfolio_idx'),
        ),
        migrations.AddIndex(
            model_name='holdingsnapshot',
            index=models.Index(fields=['stock', 'date'], name='holding_stock_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holdingsnapshot',
            unique_together={('portfolio', 'stock', 'date')},
        ),
    ]
