# Generated by Django 5.1.7 on 2025-09-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_fxrate_and_base_currency'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fxrate',
            new_name='portfolio_f_date_3f5a11_idx',
            old_name='portfolio_fx_date_idx',
        ),
        migrations.RenameIndex(
            model_name='fxrate',
            new_name='portfolio_f_base_cu_6e046d_idx',
            old_name='portfolio_fx_pair_idx',
        ),
        migrations.RenameIndex(
            model_name='fxrate',
            new_name='portfolio_f_rate_ty_832e77_idx',
            old_name='portfolio_fx_type_session_idx',
        ),
    ]
