# Generated by Django 5.1.7 on 2025-10-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_rename_portfolio_fx_date_idx_portfolio_f_date_3f5a11_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fx_rate',
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text='FX rate applied for cross-currency transactions (e.g., 3.464000)',
                max_digits=10,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fx_rate_type',
            field=models.CharField(
                blank=True,
                choices=[('compra', 'Compra'), ('venta', 'Venta'), ('mid', 'Mid')],
                help_text='Type of FX rate used (compra for sell, venta for buy)',
                max_length=10,
                null=True
            ),
        ),
    ]
