# Generated by Django 5.1.7 on 2025-10-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_add_fx_rate_to_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='realizedpnl',
            name='acquisition_date',
            field=models.DateTimeField(blank=True, help_text='Date when the shares were originally acquired (for holding period calculation)', null=True),
        ),
    ]
