# Generated by Django 5.1.7 on 2025-11-08 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_realizedpnl_acquisition_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalStockPrice',
        ),
    ]
