# Generated by Django 5.1.7 on 2026-04-17 19:15

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_delete_historicalstockprice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cash_balance_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='reporting_currency',
            field=models.CharField(default='PEN', help_text='Default currency used for dashboard/reporting metrics (e.g., PEN, USD)', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cash_currency',
            field=models.CharField(blank=True, help_text='Currency of the cash wallet affected by the transaction (e.g., PEN, USD)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='counter_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount received in counter_currency for FX conversion transactions', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='counter_currency',
            field=models.CharField(blank=True, help_text='Target currency for FX conversion transactions', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy Order'), ('SELL', 'Sell Order'), ('DEPOSIT', 'Cash Deposit'), ('WITHDRAWAL', 'Cash Withdrawal'), ('CONVERT', 'FX Conversion')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.CheckConstraint(condition=models.Q(('cash_balance_usd__gte', 0)), name='cash_balance_usd_non_negative'),
        ),
    ]
