# Generated by Django 5.1.7 on 2026-04-24 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_portfolio_cash_balance_usd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('provider', models.CharField(default='fmp', max_length=32)),
                ('provider_symbol', models.CharField(max_length=32)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BenchmarkPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('close', models.DecimalField(decimal_places=6, max_digits=18)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='portfolio.benchmarkseries')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'series'], name='benchmark_date_series_idx')],
                'constraints': [models.UniqueConstraint(fields=('series', 'date'), name='unique_benchmark_series_date')],
            },
        ),
    ]
